POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sbGkiLCJpZCI6IjVjZTY3ZjhmMTZhMzJhMzAwY2U2OGQxNSIsImlhdCI6MTU1ODYyMTE4MH0.5wp-fJS3H05iVQWC6eIQQWcpPoKdWyq-zFOSToKjLkI

{
	"title": "fishing",
	"author": "",
	"url": "www://films.html",
	"likes": 4
}